// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler/lianjia.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 房子信息
type HouseInfo struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title                string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle             string           `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Region               string           `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	BaseInfo             *BaseInfo        `protobuf:"bytes,6,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	TransactionInfo      *TransactionInfo `protobuf:"bytes,7,opt,name=transaction_info,json=transactionInfo,proto3" json:"transaction_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HouseInfo) Reset()         { *m = HouseInfo{} }
func (m *HouseInfo) String() string { return proto.CompactTextString(m) }
func (*HouseInfo) ProtoMessage()    {}
func (*HouseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{0}
}

func (m *HouseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseInfo.Unmarshal(m, b)
}
func (m *HouseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseInfo.Marshal(b, m, deterministic)
}
func (m *HouseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseInfo.Merge(m, src)
}
func (m *HouseInfo) XXX_Size() int {
	return xxx_messageInfo_HouseInfo.Size(m)
}
func (m *HouseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HouseInfo proto.InternalMessageInfo

func (m *HouseInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HouseInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HouseInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HouseInfo) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *HouseInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *HouseInfo) GetBaseInfo() *BaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *HouseInfo) GetTransactionInfo() *TransactionInfo {
	if m != nil {
		return m.TransactionInfo
	}
	return nil
}

// 基本信息
type BaseInfo struct {
	Layout               string   `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Floor                string   `protobuf:"bytes,2,opt,name=floor,proto3" json:"floor,omitempty"`
	AreaBuild            string   `protobuf:"bytes,3,opt,name=area_build,json=areaBuild,proto3" json:"area_build,omitempty"`
	StructHouse          string   `protobuf:"bytes,4,opt,name=struct_house,json=structHouse,proto3" json:"struct_house,omitempty"`
	AreaInner            string   `protobuf:"bytes,5,opt,name=area_inner,json=areaInner,proto3" json:"area_inner,omitempty"`
	BuildType            string   `protobuf:"bytes,6,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	Face                 string   `protobuf:"bytes,7,opt,name=face,proto3" json:"face,omitempty"`
	StructBuild          string   `protobuf:"bytes,8,opt,name=struct_build,json=structBuild,proto3" json:"struct_build,omitempty"`
	Decoration           string   `protobuf:"bytes,9,opt,name=decoration,proto3" json:"decoration,omitempty"`
	ElevatorRatio        string   `protobuf:"bytes,10,opt,name=elevator_ratio,json=elevatorRatio,proto3" json:"elevator_ratio,omitempty"`
	Elevator             string   `protobuf:"bytes,11,opt,name=elevator,proto3" json:"elevator,omitempty"`
	Property             string   `protobuf:"bytes,12,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{1}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *BaseInfo) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *BaseInfo) GetAreaBuild() string {
	if m != nil {
		return m.AreaBuild
	}
	return ""
}

func (m *BaseInfo) GetStructHouse() string {
	if m != nil {
		return m.StructHouse
	}
	return ""
}

func (m *BaseInfo) GetAreaInner() string {
	if m != nil {
		return m.AreaInner
	}
	return ""
}

func (m *BaseInfo) GetBuildType() string {
	if m != nil {
		return m.BuildType
	}
	return ""
}

func (m *BaseInfo) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *BaseInfo) GetStructBuild() string {
	if m != nil {
		return m.StructBuild
	}
	return ""
}

func (m *BaseInfo) GetDecoration() string {
	if m != nil {
		return m.Decoration
	}
	return ""
}

func (m *BaseInfo) GetElevatorRatio() string {
	if m != nil {
		return m.ElevatorRatio
	}
	return ""
}

func (m *BaseInfo) GetElevator() string {
	if m != nil {
		return m.Elevator
	}
	return ""
}

func (m *BaseInfo) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

// 交易信息
type TransactionInfo struct {
	ListingTime          string   `protobuf:"bytes,1,opt,name=listing_time,json=listingTime,proto3" json:"listing_time,omitempty"`
	TradingAuthority     string   `protobuf:"bytes,2,opt,name=trading_authority,json=tradingAuthority,proto3" json:"trading_authority,omitempty"`
	LastTransaction      string   `protobuf:"bytes,3,opt,name=last_transaction,json=lastTransaction,proto3" json:"last_transaction,omitempty"`
	HousingPurposes      string   `protobuf:"bytes,4,opt,name=housing_purposes,json=housingPurposes,proto3" json:"housing_purposes,omitempty"`
	HouseYear            string   `protobuf:"bytes,5,opt,name=house_year,json=houseYear,proto3" json:"house_year,omitempty"`
	PropertyRights       string   `protobuf:"bytes,6,opt,name=property_rights,json=propertyRights,proto3" json:"property_rights,omitempty"`
	MortgageInfo         string   `protobuf:"bytes,7,opt,name=mortgage_info,json=mortgageInfo,proto3" json:"mortgage_info,omitempty"`
	DocumentPhoto        string   `protobuf:"bytes,8,opt,name=document_photo,json=documentPhoto,proto3" json:"document_photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInfo) Reset()         { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()    {}
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{2}
}

func (m *TransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInfo.Unmarshal(m, b)
}
func (m *TransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInfo.Marshal(b, m, deterministic)
}
func (m *TransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInfo.Merge(m, src)
}
func (m *TransactionInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionInfo.Size(m)
}
func (m *TransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInfo proto.InternalMessageInfo

func (m *TransactionInfo) GetListingTime() string {
	if m != nil {
		return m.ListingTime
	}
	return ""
}

func (m *TransactionInfo) GetTradingAuthority() string {
	if m != nil {
		return m.TradingAuthority
	}
	return ""
}

func (m *TransactionInfo) GetLastTransaction() string {
	if m != nil {
		return m.LastTransaction
	}
	return ""
}

func (m *TransactionInfo) GetHousingPurposes() string {
	if m != nil {
		return m.HousingPurposes
	}
	return ""
}

func (m *TransactionInfo) GetHouseYear() string {
	if m != nil {
		return m.HouseYear
	}
	return ""
}

func (m *TransactionInfo) GetPropertyRights() string {
	if m != nil {
		return m.PropertyRights
	}
	return ""
}

func (m *TransactionInfo) GetMortgageInfo() string {
	if m != nil {
		return m.MortgageInfo
	}
	return ""
}

func (m *TransactionInfo) GetDocumentPhoto() string {
	if m != nil {
		return m.DocumentPhoto
	}
	return ""
}

func init() {
	proto.RegisterType((*HouseInfo)(nil), "lianjia.HouseInfo")
	proto.RegisterType((*BaseInfo)(nil), "lianjia.BaseInfo")
	proto.RegisterType((*TransactionInfo)(nil), "lianjia.TransactionInfo")
}

func init() { proto.RegisterFile("crawler/lianjia.proto", fileDescriptor_af7531cd28e23262) }

var fileDescriptor_af7531cd28e23262 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xdd, 0x8e, 0xd3, 0x3c,
	0x10, 0x86, 0xd5, 0xee, 0x5f, 0x33, 0xfd, 0x5d, 0xeb, 0xfb, 0x50, 0x60, 0x05, 0x5a, 0x8a, 0x56,
	0x2c, 0x42, 0xea, 0x4a, 0x70, 0x05, 0x94, 0x13, 0xf6, 0x6c, 0x15, 0xf5, 0x04, 0x4e, 0x22, 0x27,
	0x99, 0xa6, 0x46, 0x69, 0x1c, 0x39, 0xe3, 0x45, 0xb9, 0x46, 0xae, 0x05, 0xae, 0x01, 0x79, 0x62,
	0x77, 0x0b, 0x47, 0xf5, 0x3c, 0x33, 0x1e, 0xcf, 0xbc, 0x6f, 0x03, 0xff, 0xe7, 0x46, 0xfe, 0xa8,
	0xd0, 0xdc, 0x55, 0x4a, 0xd6, 0xdf, 0x95, 0x5c, 0x35, 0x46, 0x93, 0x16, 0x17, 0x3e, 0x5c, 0xfe,
	0x1a, 0x40, 0xf4, 0x45, 0xdb, 0x16, 0xef, 0xeb, 0xad, 0x16, 0x33, 0x18, 0xaa, 0x22, 0x1e, 0x5c,
	0x0f, 0x6e, 0xa3, 0x64, 0xa8, 0x0a, 0xb1, 0x80, 0x13, 0x6b, 0xaa, 0x78, 0xc8, 0xc0, 0x1d, 0xc5,
	0x7f, 0x70, 0x46, 0x8a, 0x2a, 0x8c, 0x4f, 0x98, 0xf5, 0x81, 0xb8, 0x82, 0xa8, 0xb5, 0x59, 0xda,
	0x67, 0x4e, 0x39, 0x33, 0x6a, 0x6d, 0xb6, 0xe1, 0xe4, 0x33, 0x38, 0x37, 0x58, 0x2a, 0x5d, 0xc7,
	0x67, 0x9c, 0xf1, 0x91, 0x58, 0x41, 0x94, 0xc9, 0x16, 0x53, 0x55, 0x6f, 0x75, 0x7c, 0x7e, 0x3d,
	0xb8, 0x1d, 0x7f, 0xb8, 0x5c, 0x85, 0x31, 0xd7, 0xb2, 0x1f, 0x29, 0x19, 0x65, 0xfe, 0x24, 0x3e,
	0xc3, 0x82, 0x8c, 0xac, 0x5b, 0x99, 0x93, 0xd2, 0x75, 0x7f, 0xed, 0x82, 0xaf, 0xc5, 0x87, 0x6b,
	0x9b, 0xa7, 0x02, 0xbe, 0x3d, 0xa7, 0xbf, 0xc1, 0xf2, 0xf7, 0x10, 0x46, 0xa1, 0xb7, 0x9b, 0xac,
	0x92, 0x9d, 0xb6, 0xe4, 0x57, 0xf6, 0x91, 0x5b, 0x72, 0x5b, 0x69, 0x6d, 0xfc, 0xe2, 0x7d, 0x20,
	0x5e, 0x02, 0x48, 0x83, 0x32, 0xcd, 0xac, 0xaa, 0x0a, 0xbf, 0x7f, 0xe4, 0xc8, 0xda, 0x01, 0xf1,
	0x1a, 0x26, 0x2d, 0x19, 0x9b, 0x53, 0xba, 0x73, 0x7a, 0x7a, 0x19, 0xc6, 0x3d, 0x63, 0x89, 0x0f,
	0x1d, 0x54, 0x5d, 0xa3, 0xf1, 0x6a, 0x70, 0x87, 0x7b, 0x07, 0x5c, 0x9a, 0x7b, 0xa7, 0xd4, 0x35,
	0xc8, 0x8a, 0x44, 0x49, 0xc4, 0x64, 0xd3, 0x35, 0x28, 0x04, 0x9c, 0x6e, 0x65, 0x8e, 0xbc, 0x73,
	0x94, 0xf0, 0xf9, 0xe8, 0xd1, 0x7e, 0xaa, 0xd1, 0xf1, 0xa3, 0xfd, 0x5c, 0xaf, 0x00, 0x0a, 0xcc,
	0xb5, 0x91, 0x4e, 0x83, 0x38, 0xe2, 0x82, 0x23, 0x22, 0x6e, 0x60, 0x86, 0x15, 0x3e, 0x4a, 0xd2,
	0x26, 0x65, 0x14, 0x03, 0xd7, 0x4c, 0x03, 0x4d, 0x1c, 0x14, 0x2f, 0x60, 0x14, 0x40, 0x3c, 0xee,
	0x1d, 0x0e, 0xb1, 0xcb, 0x35, 0x46, 0x37, 0x68, 0xa8, 0x8b, 0x27, 0x7d, 0x2e, 0xc4, 0xcb, 0x9f,
	0x43, 0x98, 0xff, 0xe3, 0x8a, 0x9b, 0xba, 0x52, 0x2d, 0xa9, 0xba, 0x4c, 0x49, 0xed, 0xd1, 0xab,
	0x3f, 0xf6, 0x6c, 0xa3, 0xf6, 0x28, 0xde, 0xc3, 0x25, 0x19, 0x59, 0xb8, 0x12, 0x69, 0x69, 0xa7,
	0x8d, 0xa2, 0xce, 0xdb, 0xb1, 0xf0, 0x89, 0x4f, 0x81, 0x8b, 0x77, 0xb0, 0xa8, 0x64, 0x4b, 0xe9,
	0x91, 0xd9, 0xde, 0x9f, 0xb9, 0xe3, 0x47, 0xcf, 0xbb, 0x52, 0x67, 0x8f, 0xeb, 0xdb, 0x58, 0xd3,
	0xe8, 0x16, 0x5b, 0xef, 0xd4, 0xdc, 0xf3, 0x07, 0x8f, 0x9d, 0x1d, 0xec, 0x64, 0xda, 0xa1, 0x3c,
	0xb8, 0xc5, 0xe4, 0x2b, 0x4a, 0x23, 0xde, 0xc2, 0x3c, 0x2c, 0x99, 0x1a, 0x55, 0xee, 0xa8, 0xf5,
	0x96, 0xcd, 0x02, 0x4e, 0x98, 0x8a, 0x37, 0x30, 0xdd, 0x6b, 0x43, 0xa5, 0x2c, 0xf1, 0xe9, 0x4f,
	0x1b, 0x25, 0x93, 0x00, 0x59, 0x92, 0x1b, 0x98, 0x15, 0x3a, 0xb7, 0x7b, 0xac, 0x29, 0x6d, 0x76,
	0x9a, 0xb4, 0xb7, 0x72, 0x1a, 0xe8, 0x83, 0x83, 0xeb, 0xab, 0x6f, 0xcf, 0x4b, 0xbd, 0xea, 0x3a,
	0x8b, 0xab, 0x02, 0x1f, 0xef, 0xc2, 0xc7, 0xcd, 0x1f, 0x75, 0x76, 0xce, 0x3f, 0x1f, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xba, 0x38, 0xa6, 0xf4, 0x03, 0x00, 0x00,
}
