// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler/lianjia.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HouseSummary is house list info summary
type HouseSummary struct {
	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo     string `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	TotalPrice  string `protobuf:"bytes,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UnitPrice   string `protobuf:"bytes,6,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Plot        string `protobuf:"bytes,7,opt,name=plot,proto3" json:"plot,omitempty"`
	Region      string `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	Layout      string `protobuf:"bytes,9,opt,name=layout,proto3" json:"layout,omitempty"`
	Area        string `protobuf:"bytes,10,opt,name=area,proto3" json:"area,omitempty"`
	Face        string `protobuf:"bytes,11,opt,name=face,proto3" json:"face,omitempty"`
	Decoration  string `protobuf:"bytes,12,opt,name=decoration,proto3" json:"decoration,omitempty"`
	Floor       string `protobuf:"bytes,13,opt,name=floor,proto3" json:"floor,omitempty"`
	HouseYear   string `protobuf:"bytes,14,opt,name=house_year,json=houseYear,proto3" json:"house_year,omitempty"`
	StructBuild string `protobuf:"bytes,15,opt,name=struct_build,json=structBuild,proto3" json:"struct_build,omitempty"`
	Image       string `protobuf:"bytes,16,opt,name=image,proto3" json:"image,omitempty"`
	Follow      int32  `protobuf:"varint,17,opt,name=follow,proto3" json:"follow,omitempty"`
	ReleaseTime string `protobuf:"bytes,18,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	// tags 1: 必看好房 2: 房本满五年 4: 房本满两年 8: VR房源 16: 近地铁 32: 随时看房
	Tags                 int32    `protobuf:"varint,19,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseSummary) Reset()         { *m = HouseSummary{} }
func (m *HouseSummary) String() string { return proto.CompactTextString(m) }
func (*HouseSummary) ProtoMessage()    {}
func (*HouseSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{0}
}

func (m *HouseSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseSummary.Unmarshal(m, b)
}
func (m *HouseSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseSummary.Marshal(b, m, deterministic)
}
func (m *HouseSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseSummary.Merge(m, src)
}
func (m *HouseSummary) XXX_Size() int {
	return xxx_messageInfo_HouseSummary.Size(m)
}
func (m *HouseSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseSummary.DiscardUnknown(m)
}

var xxx_messageInfo_HouseSummary proto.InternalMessageInfo

func (m *HouseSummary) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HouseSummary) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *HouseSummary) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HouseSummary) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HouseSummary) GetTotalPrice() string {
	if m != nil {
		return m.TotalPrice
	}
	return ""
}

func (m *HouseSummary) GetUnitPrice() string {
	if m != nil {
		return m.UnitPrice
	}
	return ""
}

func (m *HouseSummary) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

func (m *HouseSummary) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *HouseSummary) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *HouseSummary) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *HouseSummary) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *HouseSummary) GetDecoration() string {
	if m != nil {
		return m.Decoration
	}
	return ""
}

func (m *HouseSummary) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *HouseSummary) GetHouseYear() string {
	if m != nil {
		return m.HouseYear
	}
	return ""
}

func (m *HouseSummary) GetStructBuild() string {
	if m != nil {
		return m.StructBuild
	}
	return ""
}

func (m *HouseSummary) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *HouseSummary) GetFollow() int32 {
	if m != nil {
		return m.Follow
	}
	return 0
}

func (m *HouseSummary) GetReleaseTime() string {
	if m != nil {
		return m.ReleaseTime
	}
	return ""
}

func (m *HouseSummary) GetTags() int32 {
	if m != nil {
		return m.Tags
	}
	return 0
}

type House struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo              string                `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	HouseInfo            *HouseInfo            `protobuf:"bytes,3,opt,name=house_info,json=houseInfo,proto3" json:"house_info,omitempty"`
	HouseBaseInfo        *HouseBaseInfo        `protobuf:"bytes,4,opt,name=house_base_info,json=houseBaseInfo,proto3" json:"house_base_info,omitempty"`
	HouseTransactionInfo *HouseTransactionInfo `protobuf:"bytes,5,opt,name=house_transaction_info,json=houseTransactionInfo,proto3" json:"house_transaction_info,omitempty"`
	HousePics            []*HousePic           `protobuf:"bytes,6,rep,name=house_pics,json=housePics,proto3" json:"house_pics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *House) Reset()         { *m = House{} }
func (m *House) String() string { return proto.CompactTextString(m) }
func (*House) ProtoMessage()    {}
func (*House) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{1}
}

func (m *House) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_House.Unmarshal(m, b)
}
func (m *House) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_House.Marshal(b, m, deterministic)
}
func (m *House) XXX_Merge(src proto.Message) {
	xxx_messageInfo_House.Merge(m, src)
}
func (m *House) XXX_Size() int {
	return xxx_messageInfo_House.Size(m)
}
func (m *House) XXX_DiscardUnknown() {
	xxx_messageInfo_House.DiscardUnknown(m)
}

var xxx_messageInfo_House proto.InternalMessageInfo

func (m *House) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *House) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *House) GetHouseInfo() *HouseInfo {
	if m != nil {
		return m.HouseInfo
	}
	return nil
}

func (m *House) GetHouseBaseInfo() *HouseBaseInfo {
	if m != nil {
		return m.HouseBaseInfo
	}
	return nil
}

func (m *House) GetHouseTransactionInfo() *HouseTransactionInfo {
	if m != nil {
		return m.HouseTransactionInfo
	}
	return nil
}

func (m *House) GetHousePics() []*HousePic {
	if m != nil {
		return m.HousePics
	}
	return nil
}

// 房子信息
type HouseInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo              string   `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle             string   `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Region               string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	TotalPrice           string   `protobuf:"bytes,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UnitPrice            string   `protobuf:"bytes,8,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	RoomInfo             string   `protobuf:"bytes,9,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	RoomSub              string   `protobuf:"bytes,10,opt,name=room_sub,json=roomSub,proto3" json:"room_sub,omitempty"`
	TypeInfo             string   `protobuf:"bytes,11,opt,name=type_info,json=typeInfo,proto3" json:"type_info,omitempty"`
	TypeSub              string   `protobuf:"bytes,12,opt,name=type_sub,json=typeSub,proto3" json:"type_sub,omitempty"`
	AreaInfo             string   `protobuf:"bytes,13,opt,name=area_info,json=areaInfo,proto3" json:"area_info,omitempty"`
	AreaSub              string   `protobuf:"bytes,14,opt,name=area_sub,json=areaSub,proto3" json:"area_sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseInfo) Reset()         { *m = HouseInfo{} }
func (m *HouseInfo) String() string { return proto.CompactTextString(m) }
func (*HouseInfo) ProtoMessage()    {}
func (*HouseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{2}
}

func (m *HouseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseInfo.Unmarshal(m, b)
}
func (m *HouseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseInfo.Marshal(b, m, deterministic)
}
func (m *HouseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseInfo.Merge(m, src)
}
func (m *HouseInfo) XXX_Size() int {
	return xxx_messageInfo_HouseInfo.Size(m)
}
func (m *HouseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HouseInfo proto.InternalMessageInfo

func (m *HouseInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HouseInfo) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *HouseInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HouseInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HouseInfo) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *HouseInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *HouseInfo) GetTotalPrice() string {
	if m != nil {
		return m.TotalPrice
	}
	return ""
}

func (m *HouseInfo) GetUnitPrice() string {
	if m != nil {
		return m.UnitPrice
	}
	return ""
}

func (m *HouseInfo) GetRoomInfo() string {
	if m != nil {
		return m.RoomInfo
	}
	return ""
}

func (m *HouseInfo) GetRoomSub() string {
	if m != nil {
		return m.RoomSub
	}
	return ""
}

func (m *HouseInfo) GetTypeInfo() string {
	if m != nil {
		return m.TypeInfo
	}
	return ""
}

func (m *HouseInfo) GetTypeSub() string {
	if m != nil {
		return m.TypeSub
	}
	return ""
}

func (m *HouseInfo) GetAreaInfo() string {
	if m != nil {
		return m.AreaInfo
	}
	return ""
}

func (m *HouseInfo) GetAreaSub() string {
	if m != nil {
		return m.AreaSub
	}
	return ""
}

// 基本信息
type HouseBaseInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo              string   `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	Layout               string   `protobuf:"bytes,3,opt,name=layout,proto3" json:"layout,omitempty"`
	Floor                string   `protobuf:"bytes,4,opt,name=floor,proto3" json:"floor,omitempty"`
	AreaBuild            string   `protobuf:"bytes,5,opt,name=area_build,json=areaBuild,proto3" json:"area_build,omitempty"`
	StructHouse          string   `protobuf:"bytes,6,opt,name=struct_house,json=structHouse,proto3" json:"struct_house,omitempty"`
	AreaInner            string   `protobuf:"bytes,7,opt,name=area_inner,json=areaInner,proto3" json:"area_inner,omitempty"`
	BuildType            string   `protobuf:"bytes,8,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	Face                 string   `protobuf:"bytes,9,opt,name=face,proto3" json:"face,omitempty"`
	StructBuild          string   `protobuf:"bytes,10,opt,name=struct_build,json=structBuild,proto3" json:"struct_build,omitempty"`
	Decoration           string   `protobuf:"bytes,11,opt,name=decoration,proto3" json:"decoration,omitempty"`
	ElevatorRatio        string   `protobuf:"bytes,12,opt,name=elevator_ratio,json=elevatorRatio,proto3" json:"elevator_ratio,omitempty"`
	Elevator             string   `protobuf:"bytes,13,opt,name=elevator,proto3" json:"elevator,omitempty"`
	Property             string   `protobuf:"bytes,14,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseBaseInfo) Reset()         { *m = HouseBaseInfo{} }
func (m *HouseBaseInfo) String() string { return proto.CompactTextString(m) }
func (*HouseBaseInfo) ProtoMessage()    {}
func (*HouseBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{3}
}

func (m *HouseBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseBaseInfo.Unmarshal(m, b)
}
func (m *HouseBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseBaseInfo.Marshal(b, m, deterministic)
}
func (m *HouseBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseBaseInfo.Merge(m, src)
}
func (m *HouseBaseInfo) XXX_Size() int {
	return xxx_messageInfo_HouseBaseInfo.Size(m)
}
func (m *HouseBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HouseBaseInfo proto.InternalMessageInfo

func (m *HouseBaseInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HouseBaseInfo) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *HouseBaseInfo) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *HouseBaseInfo) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *HouseBaseInfo) GetAreaBuild() string {
	if m != nil {
		return m.AreaBuild
	}
	return ""
}

func (m *HouseBaseInfo) GetStructHouse() string {
	if m != nil {
		return m.StructHouse
	}
	return ""
}

func (m *HouseBaseInfo) GetAreaInner() string {
	if m != nil {
		return m.AreaInner
	}
	return ""
}

func (m *HouseBaseInfo) GetBuildType() string {
	if m != nil {
		return m.BuildType
	}
	return ""
}

func (m *HouseBaseInfo) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *HouseBaseInfo) GetStructBuild() string {
	if m != nil {
		return m.StructBuild
	}
	return ""
}

func (m *HouseBaseInfo) GetDecoration() string {
	if m != nil {
		return m.Decoration
	}
	return ""
}

func (m *HouseBaseInfo) GetElevatorRatio() string {
	if m != nil {
		return m.ElevatorRatio
	}
	return ""
}

func (m *HouseBaseInfo) GetElevator() string {
	if m != nil {
		return m.Elevator
	}
	return ""
}

func (m *HouseBaseInfo) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

// 交易信息
type HouseTransactionInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo              string   `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	ListingTime          string   `protobuf:"bytes,3,opt,name=listing_time,json=listingTime,proto3" json:"listing_time,omitempty"`
	TradingAuthority     string   `protobuf:"bytes,4,opt,name=trading_authority,json=tradingAuthority,proto3" json:"trading_authority,omitempty"`
	LastTransaction      string   `protobuf:"bytes,5,opt,name=last_transaction,json=lastTransaction,proto3" json:"last_transaction,omitempty"`
	HousingPurposes      string   `protobuf:"bytes,6,opt,name=housing_purposes,json=housingPurposes,proto3" json:"housing_purposes,omitempty"`
	HouseYear            string   `protobuf:"bytes,7,opt,name=house_year,json=houseYear,proto3" json:"house_year,omitempty"`
	PropertyRights       string   `protobuf:"bytes,8,opt,name=property_rights,json=propertyRights,proto3" json:"property_rights,omitempty"`
	MortgageInfo         string   `protobuf:"bytes,9,opt,name=mortgage_info,json=mortgageInfo,proto3" json:"mortgage_info,omitempty"`
	DocumentPhoto        string   `protobuf:"bytes,10,opt,name=document_photo,json=documentPhoto,proto3" json:"document_photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseTransactionInfo) Reset()         { *m = HouseTransactionInfo{} }
func (m *HouseTransactionInfo) String() string { return proto.CompactTextString(m) }
func (*HouseTransactionInfo) ProtoMessage()    {}
func (*HouseTransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{4}
}

func (m *HouseTransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseTransactionInfo.Unmarshal(m, b)
}
func (m *HouseTransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseTransactionInfo.Marshal(b, m, deterministic)
}
func (m *HouseTransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseTransactionInfo.Merge(m, src)
}
func (m *HouseTransactionInfo) XXX_Size() int {
	return xxx_messageInfo_HouseTransactionInfo.Size(m)
}
func (m *HouseTransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseTransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HouseTransactionInfo proto.InternalMessageInfo

func (m *HouseTransactionInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HouseTransactionInfo) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *HouseTransactionInfo) GetListingTime() string {
	if m != nil {
		return m.ListingTime
	}
	return ""
}

func (m *HouseTransactionInfo) GetTradingAuthority() string {
	if m != nil {
		return m.TradingAuthority
	}
	return ""
}

func (m *HouseTransactionInfo) GetLastTransaction() string {
	if m != nil {
		return m.LastTransaction
	}
	return ""
}

func (m *HouseTransactionInfo) GetHousingPurposes() string {
	if m != nil {
		return m.HousingPurposes
	}
	return ""
}

func (m *HouseTransactionInfo) GetHouseYear() string {
	if m != nil {
		return m.HouseYear
	}
	return ""
}

func (m *HouseTransactionInfo) GetPropertyRights() string {
	if m != nil {
		return m.PropertyRights
	}
	return ""
}

func (m *HouseTransactionInfo) GetMortgageInfo() string {
	if m != nil {
		return m.MortgageInfo
	}
	return ""
}

func (m *HouseTransactionInfo) GetDocumentPhoto() string {
	if m != nil {
		return m.DocumentPhoto
	}
	return ""
}

// 照片
type HousePic struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseNo              string   `protobuf:"bytes,2,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PicSmallUrl          string   `protobuf:"bytes,4,opt,name=pic_small_url,json=picSmallUrl,proto3" json:"pic_small_url,omitempty"`
	PicNormalUrl         string   `protobuf:"bytes,5,opt,name=pic_normal_url,json=picNormalUrl,proto3" json:"pic_normal_url,omitempty"`
	PicLargeUrl          string   `protobuf:"bytes,6,opt,name=pic_large_url,json=picLargeUrl,proto3" json:"pic_large_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousePic) Reset()         { *m = HousePic{} }
func (m *HousePic) String() string { return proto.CompactTextString(m) }
func (*HousePic) ProtoMessage()    {}
func (*HousePic) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7531cd28e23262, []int{5}
}

func (m *HousePic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousePic.Unmarshal(m, b)
}
func (m *HousePic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousePic.Marshal(b, m, deterministic)
}
func (m *HousePic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousePic.Merge(m, src)
}
func (m *HousePic) XXX_Size() int {
	return xxx_messageInfo_HousePic.Size(m)
}
func (m *HousePic) XXX_DiscardUnknown() {
	xxx_messageInfo_HousePic.DiscardUnknown(m)
}

var xxx_messageInfo_HousePic proto.InternalMessageInfo

func (m *HousePic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HousePic) GetHouseNo() string {
	if m != nil {
		return m.HouseNo
	}
	return ""
}

func (m *HousePic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *HousePic) GetPicSmallUrl() string {
	if m != nil {
		return m.PicSmallUrl
	}
	return ""
}

func (m *HousePic) GetPicNormalUrl() string {
	if m != nil {
		return m.PicNormalUrl
	}
	return ""
}

func (m *HousePic) GetPicLargeUrl() string {
	if m != nil {
		return m.PicLargeUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*HouseSummary)(nil), "lianjia.HouseSummary")
	proto.RegisterType((*House)(nil), "lianjia.House")
	proto.RegisterType((*HouseInfo)(nil), "lianjia.HouseInfo")
	proto.RegisterType((*HouseBaseInfo)(nil), "lianjia.HouseBaseInfo")
	proto.RegisterType((*HouseTransactionInfo)(nil), "lianjia.HouseTransactionInfo")
	proto.RegisterType((*HousePic)(nil), "lianjia.HousePic")
}

func init() { proto.RegisterFile("crawler/lianjia.proto", fileDescriptor_af7531cd28e23262) }

var fileDescriptor_af7531cd28e23262 = []byte{
	// 923 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x6e, 0x24, 0x35,
	0x10, 0x55, 0x66, 0x32, 0xb7, 0x9a, 0x5b, 0x62, 0x42, 0xe4, 0x10, 0x2d, 0x64, 0x07, 0x56, 0x04,
	0x21, 0x65, 0x61, 0x79, 0x47, 0x22, 0x4f, 0x20, 0xa1, 0xd5, 0x28, 0x93, 0x7d, 0x80, 0x97, 0x96,
	0xa7, 0xc7, 0xd3, 0x63, 0xe4, 0x6e, 0xb7, 0xdc, 0xee, 0x5d, 0xf5, 0xcf, 0xf0, 0x05, 0xfc, 0x06,
	0x3f, 0xc3, 0x2f, 0xf0, 0x82, 0xaa, 0x6c, 0xcf, 0x6d, 0x57, 0x5a, 0xf2, 0x14, 0xd7, 0x29, 0xd7,
	0x89, 0xab, 0x4e, 0x9f, 0xd2, 0xc0, 0xa7, 0xa9, 0x15, 0xef, 0xb4, 0xb4, 0x2f, 0xb5, 0x12, 0xc5,
	0x1f, 0x4a, 0xdc, 0x95, 0xd6, 0x38, 0xc3, 0x7a, 0x21, 0x9c, 0xfd, 0xd3, 0x86, 0xd1, 0xcf, 0xa6,
	0xae, 0xe4, 0xa2, 0xce, 0x73, 0x61, 0x1b, 0x36, 0x81, 0x96, 0x5a, 0xf1, 0x93, 0x9b, 0x93, 0xdb,
	0xce, 0x43, 0x4b, 0xad, 0xd8, 0x15, 0xf4, 0x37, 0x98, 0x4f, 0x0a, 0xc3, 0x5b, 0x37, 0x27, 0xb7,
	0x83, 0x87, 0x1e, 0xc5, 0xaf, 0x0d, 0x3b, 0x83, 0x76, 0x6d, 0x35, 0x6f, 0x13, 0x8a, 0x47, 0x76,
	0x01, 0x1d, 0xa7, 0x9c, 0x96, 0xfc, 0x94, 0x30, 0x1f, 0xb0, 0x2f, 0x60, 0xe8, 0x8c, 0x13, 0x3a,
	0x29, 0xad, 0x4a, 0x25, 0xef, 0x50, 0x0e, 0x08, 0x9a, 0x23, 0xc2, 0x9e, 0x01, 0xd4, 0x85, 0x72,
	0x21, 0xdf, 0xa5, 0xfc, 0x00, 0x11, 0x9f, 0x66, 0x70, 0x5a, 0x6a, 0xe3, 0x78, 0x8f, 0x12, 0x74,
	0x66, 0x97, 0xd0, 0xb5, 0x32, 0x53, 0xa6, 0xe0, 0x7d, 0x42, 0x43, 0x84, 0xb8, 0x16, 0x8d, 0xa9,
	0x1d, 0x1f, 0x78, 0xdc, 0x47, 0xc8, 0x21, 0xac, 0x14, 0x1c, 0x3c, 0x07, 0x9e, 0x11, 0x5b, 0x8b,
	0x54, 0xf2, 0xa1, 0xc7, 0xf0, 0xcc, 0x3e, 0x07, 0x58, 0xc9, 0xd4, 0x58, 0xe1, 0x90, 0x7b, 0xe4,
	0x9f, 0xba, 0x43, 0xb0, 0xc3, 0xb5, 0x36, 0xc6, 0xf2, 0xb1, 0xef, 0x90, 0x02, 0x6c, 0xc0, 0x0f,
	0xa9, 0x91, 0xc2, 0xf2, 0x89, 0x6f, 0x80, 0x90, 0xdf, 0xa4, 0xb0, 0xec, 0x39, 0x8c, 0x2a, 0x67,
	0xeb, 0xd4, 0x25, 0xcb, 0x5a, 0xe9, 0x15, 0x9f, 0xd2, 0x85, 0xa1, 0xc7, 0xee, 0x11, 0x42, 0x5e,
	0x95, 0x8b, 0x4c, 0xf2, 0x33, 0xcf, 0x4b, 0x01, 0x76, 0xb3, 0x36, 0x5a, 0x9b, 0x77, 0xfc, 0x9c,
	0x04, 0x09, 0x11, 0x12, 0x5a, 0xa9, 0xa5, 0xa8, 0x64, 0xe2, 0x54, 0x2e, 0x39, 0xf3, 0x84, 0x01,
	0x7b, 0x54, 0x39, 0x0d, 0xcd, 0x89, 0xac, 0xe2, 0x9f, 0x50, 0x21, 0x9d, 0x67, 0x7f, 0xb5, 0xa0,
	0x43, 0x62, 0xef, 0xa9, 0x3c, 0xf8, 0x98, 0xca, 0xdf, 0xc7, 0xde, 0x54, 0xb1, 0x36, 0x24, 0xf6,
	0xf0, 0x15, 0xbb, 0x8b, 0x9f, 0x13, 0xd1, 0xfd, 0x52, 0xac, 0x4d, 0xe8, 0x17, 0x8f, 0xec, 0x47,
	0x98, 0xfa, 0x92, 0xa5, 0x88, 0x75, 0xa7, 0x54, 0x77, 0x79, 0x58, 0x77, 0x2f, 0x42, 0xed, 0x78,
	0xb3, 0x1f, 0xb2, 0x05, 0x5c, 0xfa, 0x7a, 0x67, 0x45, 0x51, 0x89, 0x14, 0x27, 0xef, 0x69, 0x3a,
	0x44, 0xf3, 0xec, 0x90, 0xe6, 0x71, 0x77, 0x8b, 0xd8, 0x2e, 0x36, 0x1f, 0x40, 0xd9, 0x77, 0xb1,
	0x8f, 0x52, 0xa5, 0x15, 0xef, 0xde, 0xb4, 0x6f, 0x87, 0xaf, 0xce, 0x0f, 0x89, 0xe6, 0x2a, 0x0d,
	0x6d, 0xcc, 0x55, 0x5a, 0xcd, 0xfe, 0x6d, 0xc1, 0x60, 0xdb, 0xdf, 0x53, 0x46, 0xf6, 0x7f, 0x8d,
	0x71, 0x0d, 0x83, 0xaa, 0x5e, 0x26, 0x3e, 0xe3, 0x6d, 0xd1, 0xaf, 0xea, 0xe5, 0x23, 0x25, 0x77,
	0x5f, 0x78, 0xf7, 0xe0, 0x0b, 0x3f, 0x72, 0x53, 0xef, 0x23, 0x6e, 0xea, 0x1f, 0xbb, 0xe9, 0x1a,
	0x06, 0xd6, 0x98, 0xdc, 0xcf, 0xd3, 0x9b, 0xa4, 0x8f, 0x00, 0x35, 0x79, 0x05, 0x74, 0x4e, 0xaa,
	0x7a, 0x19, 0xac, 0xd2, 0xc3, 0x78, 0x51, 0x2f, 0xb1, 0xce, 0x35, 0x65, 0x90, 0xd3, 0x5b, 0xa6,
	0x8f, 0x40, 0xac, 0xa3, 0x24, 0xd6, 0x79, 0xd3, 0xf4, 0x30, 0x0e, 0x75, 0xe8, 0x36, 0x5f, 0xe7,
	0x5d, 0xd3, 0x47, 0x20, 0xd6, 0x51, 0x12, 0xeb, 0xbc, 0x6d, 0x7a, 0x18, 0x2f, 0xea, 0xe5, 0xec,
	0xcf, 0x36, 0x8c, 0x0f, 0xbe, 0x92, 0xa7, 0x28, 0xb0, 0x5b, 0x03, 0xed, 0x83, 0x35, 0xb0, 0xb5,
	0xef, 0xe9, 0x91, 0x7d, 0xe9, 0x15, 0xde, 0x9d, 0x5e, 0x08, 0x7a, 0xb4, 0xf7, 0xe6, 0xce, 0xbe,
	0x44, 0x1f, 0xf4, 0x08, 0xf6, 0xf5, 0x7e, 0x8a, 0x0c, 0xaa, 0x28, 0xa4, 0x0d, 0x9a, 0x0c, 0x7c,
	0x97, 0x85, 0xa4, 0x7f, 0x40, 0xdc, 0x09, 0x0e, 0x25, 0x4a, 0x42, 0xc8, 0x63, 0x53, 0xca, 0xed,
	0x22, 0x1a, 0xec, 0x2d, 0xa2, 0xe3, 0x9d, 0x01, 0xef, 0xef, 0x8c, 0xc3, 0x5d, 0x35, 0x7c, 0x6f,
	0x57, 0xbd, 0x80, 0x89, 0xd4, 0xf2, 0xad, 0x70, 0xc6, 0x26, 0x04, 0x05, 0x69, 0xc6, 0x11, 0x7d,
	0x40, 0x90, 0x7d, 0x06, 0xfd, 0x08, 0x44, 0x7d, 0x62, 0x8c, 0xb9, 0xd2, 0x9a, 0x52, 0x5a, 0xd7,
	0x04, 0x7d, 0xb6, 0x31, 0xda, 0xe3, 0xe2, 0x43, 0xfe, 0x7b, 0x8a, 0x4e, 0xcf, 0x61, 0xa4, 0x55,
	0xe5, 0x54, 0x91, 0xf9, 0x45, 0xe6, 0xd5, 0x1a, 0x06, 0x8c, 0x16, 0xd9, 0xb7, 0x70, 0xee, 0xac,
	0x58, 0xe1, 0x15, 0x51, 0xbb, 0x8d, 0xb1, 0xca, 0x35, 0x41, 0xbe, 0xb3, 0x90, 0xf8, 0x29, 0xe2,
	0xec, 0x1b, 0x38, 0xd3, 0xa2, 0x72, 0xfb, 0x8b, 0x23, 0xe8, 0x39, 0x45, 0x7c, 0xef, 0xa5, 0x78,
	0x15, 0x5f, 0x81, 0xbc, 0x65, 0x6d, 0x4b, 0x53, 0xc9, 0x2a, 0x28, 0x3b, 0x0d, 0xf8, 0x3c, 0xc0,
	0x47, 0xeb, 0xbd, 0x77, 0xbc, 0xde, 0xbf, 0x86, 0x69, 0x1c, 0x4a, 0x62, 0x55, 0xb6, 0x71, 0x55,
	0x90, 0x78, 0x12, 0xe1, 0x07, 0x42, 0xd9, 0x97, 0x30, 0xce, 0x8d, 0x75, 0x99, 0xc8, 0xe4, 0xbe,
	0xfd, 0x46, 0x11, 0xa4, 0xe9, 0xbd, 0x80, 0xc9, 0xca, 0xa4, 0x75, 0x2e, 0x0b, 0x97, 0x94, 0x1b,
	0xe3, 0x4c, 0x90, 0x7e, 0x1c, 0xd1, 0x39, 0x82, 0xb3, 0xbf, 0x4f, 0xa0, 0x1f, 0x97, 0xd6, 0x53,
	0x26, 0x7e, 0x03, 0xc3, 0x95, 0xac, 0x52, 0xab, 0x4a, 0x1a, 0x4e, 0x18, 0xf8, 0x1e, 0xc4, 0x66,
	0x30, 0x2e, 0x55, 0x9a, 0x54, 0xb9, 0xd0, 0x3a, 0xc1, 0x3d, 0xe6, 0x87, 0x3d, 0x2c, 0x55, 0xba,
	0x40, 0xec, 0x8d, 0xd5, 0xec, 0x2b, 0x98, 0xe0, 0x9d, 0xc2, 0xd8, 0x5c, 0xf8, 0x4b, 0x7e, 0xca,
	0xa3, 0x52, 0xa5, 0xaf, 0x09, 0xc4, 0x5b, 0x81, 0x49, 0x0b, 0x9b, 0x49, 0xba, 0xd4, 0xdd, 0x32,
	0xfd, 0x8a, 0xd8, 0x1b, 0xab, 0xef, 0xaf, 0x7f, 0xbf, 0xca, 0xcc, 0x5d, 0xd3, 0xd4, 0xf2, 0x6e,
	0x25, 0xdf, 0xbe, 0x8c, 0x3f, 0x57, 0xe8, 0x67, 0xca, 0xb2, 0x4b, 0x7f, 0x7e, 0xf8, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x98, 0x88, 0x1c, 0xc6, 0x08, 0x00, 0x00,
}
