version: "3.6"
services:

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"

  go:
    build:
      context: .
      dockerfile: go.Dockerfile
    environment:
      GO_RUN_ENV: production
    ports:
      - "6503:6503"
    networks:
      - back

  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - back

networks:
  back:
    # Use a custom driver which takes special options
    driver: custom-driver-1