version: "3.6"
services:

  nginx:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
      
  go:
    build:
      dockerfile: go.Dockerfile
    ports:
      - "6503:6503"
