// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "go.yyue.dev/common/message"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type ValidateRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ValidateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UserInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	CreateTime           string   `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	LoginTime            string   `protobuf:"bytes,9,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UserInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *UserInfo) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetInfoRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "user.SendRequest")
	proto.RegisterType((*ValidateRequest)(nil), "user.ValidateRequest")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*GetInfoRequest)(nil), "user.GetInfoRequest")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0xdc, 0x84, 0xa4, 0x9b, 0xbe, 0x42, 0x17, 0x9e, 0xca, 0xca, 0x8a, 0x84, 0x58, 0x45, 0x42,
	0xea, 0x65, 0x53, 0xb1, 0x88, 0x23, 0x97, 0xbd, 0x20, 0x24, 0xf6, 0x92, 0x00, 0x07, 0x2e, 0x28,
	0x1b, 0x3f, 0x22, 0x4b, 0x4d, 0x5c, 0x6c, 0x67, 0x51, 0x7f, 0x0d, 0xbf, 0x90, 0xff, 0x80, 0x6c,
	0x37, 0x55, 0x5b, 0xaa, 0xed, 0xa5, 0x7e, 0x1f, 0x33, 0x63, 0x75, 0xc6, 0x81, 0x8b, 0x5e, 0x93,
	0x5a, 0xd8, 0x9f, 0x7c, 0xa5, 0xa4, 0x91, 0x18, 0xd9, 0x3a, 0x9d, 0xd5, 0xb2, 0x6d, 0x65, 0xb7,
	0x68, 0x49, 0xeb, 0xaa, 0x21, 0xbf, 0xcb, 0xde, 0xc0, 0xa4, 0xa4, 0x8e, 0x17, 0xf4, 0xab, 0x27,
	0x6d, 0xf0, 0x12, 0x46, 0xad, 0xbc, 0x17, 0x4b, 0x62, 0xc1, 0x55, 0x30, 0x1f, 0x17, 0x9b, 0x2e,
	0xfb, 0x00, 0x17, 0xdf, 0xaa, 0xa5, 0xe0, 0x95, 0xa1, 0x13, 0x50, 0x44, 0x88, 0x6a, 0xc9, 0x89,
	0x85, 0x6e, 0xea, 0xea, 0xec, 0x6f, 0x00, 0xc9, 0x57, 0x4d, 0xea, 0x53, 0xf7, 0x53, 0xe2, 0x14,
	0x42, 0xc1, 0x1d, 0xe9, 0x59, 0x11, 0x0a, 0x6e, 0x09, 0x5d, 0xd5, 0x12, 0x8b, 0x3c, 0xc1, 0xd6,
	0x3b, 0xe2, 0xe1, 0x9e, 0x78, 0x0a, 0xc9, 0xaa, 0xd2, 0xfa, 0xb7, 0x54, 0x9c, 0x3d, 0x71, 0x9b,
	0x6d, 0x6f, 0x75, 0xfa, 0x5e, 0x70, 0x16, 0x7b, 0x1d, 0x5b, 0xe3, 0x0c, 0x62, 0x6d, 0x2a, 0x43,
	0x6c, 0x74, 0x15, 0xcc, 0xe3, 0xc2, 0x37, 0xf8, 0x1a, 0x26, 0xb5, 0xa2, 0xca, 0xd0, 0x0f, 0x23,
	0x5a, 0x62, 0xe7, 0x8e, 0x00, 0x7e, 0xf4, 0x45, 0xb4, 0x0e, 0xd0, 0xaf, 0xf8, 0x16, 0x90, 0x78,
	0x80, 0x1f, 0x39, 0xc0, 0x2b, 0x80, 0xa5, 0x6c, 0x44, 0xe7, 0xf7, 0x63, 0xb7, 0x1f, 0xbb, 0x89,
	0x5d, 0x67, 0xb7, 0xf0, 0xf4, 0xb3, 0x6d, 0x4e, 0x79, 0xf5, 0xc8, 0xdf, 0xc9, 0xe6, 0x30, 0xfd,
	0x48, 0xc6, 0x3a, 0x76, 0x42, 0xe5, 0x46, 0x01, 0x94, 0x77, 0x65, 0x49, 0xea, 0x41, 0xd4, 0x84,
	0xd7, 0x10, 0xd9, 0x44, 0xf1, 0x45, 0xee, 0x9e, 0xc0, 0x4e, 0xba, 0xe9, 0xf3, 0x7c, 0x08, 0xff,
	0xce, 0x9f, 0xd9, 0x19, 0xbe, 0x87, 0x64, 0x48, 0x16, 0x5f, 0x7a, 0xca, 0x41, 0xd2, 0xc7, 0x68,
	0x37, 0x7f, 0x02, 0x98, 0xd8, 0x44, 0x87, 0x5b, 0x73, 0x48, 0x0a, 0x6a, 0x84, 0x36, 0xa4, 0x70,
	0xea, 0x65, 0x86, 0xc0, 0x8f, 0x5e, 0x7b, 0x0d, 0xb1, 0x73, 0x08, 0xd1, 0x83, 0x77, 0xed, 0x4a,
	0x0f, 0x04, 0xb2, 0x33, 0x7c, 0x0b, 0xe7, 0x1b, 0x33, 0x70, 0xe6, 0x97, 0xfb, 0xde, 0xfc, 0x4f,
	0xb9, 0x65, 0xdf, 0x2f, 0x1b, 0x99, 0xaf, 0xd7, 0x3d, 0xe5, 0x9c, 0x1e, 0xdc, 0xf7, 0xb0, 0x70,
	0x6f, 0xfe, 0x7e, 0xe4, 0x8e, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x75, 0x4b, 0xc4,
	0x29, 0x03, 0x00, 0x00,
}
