// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.10.1
// source: beike/beike.proto

package beike

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BEIKE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code float64     `protobuf:"fixed64,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *BEIKE_DATA `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg  string      `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BEIKE) Reset() {
	*x = BEIKE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE) ProtoMessage() {}

func (x *BEIKE) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE.ProtoReflect.Descriptor instead.
func (*BEIKE) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0}
}

func (x *BEIKE) GetCode() float64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BEIKE) GetData() *BEIKE_DATA {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BEIKE) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BEIKE_DATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno   float64          `protobuf:"fixed64,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Msg     string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    *BEIKE_DATA_DATA `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Errkeys []string         `protobuf:"bytes,4,rep,name=errkeys,proto3" json:"errkeys,omitempty"` // TODO
}

func (x *BEIKE_DATA) Reset() {
	*x = BEIKE_DATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA) ProtoMessage() {}

func (x *BEIKE_DATA) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BEIKE_DATA) GetErrno() float64 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *BEIKE_DATA) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BEIKE_DATA) GetData() *BEIKE_DATA_DATA {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BEIKE_DATA) GetErrkeys() []string {
	if x != nil {
		return x.Errkeys
	}
	return nil
}

type BEIKE_DATA_DATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetErShouFangList *BEIKE_DATA_DATA_GETERSHOUFANGLIST `protobuf:"bytes,1,opt,name=getErShouFangList,proto3" json:"getErShouFangList,omitempty"`
}

func (x *BEIKE_DATA_DATA) Reset() {
	*x = BEIKE_DATA_DATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA) ProtoMessage() {}

func (x *BEIKE_DATA_DATA) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *BEIKE_DATA_DATA) GetGetErShouFangList() *BEIKE_DATA_DATA_GETERSHOUFANGLIST {
	if x != nil {
		return x.GetErShouFangList
	}
	return nil
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount       float64                                             `protobuf:"fixed64,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	ReturnCount      float64                                             `protobuf:"fixed64,2,opt,name=returnCount,proto3" json:"returnCount,omitempty"`
	FbQueryId        string                                              `protobuf:"bytes,3,opt,name=fbQueryId,proto3" json:"fbQueryId,omitempty"`
	CurPage          float64                                             `protobuf:"fixed64,4,opt,name=curPage,proto3" json:"curPage,omitempty"`
	HasMoreData      float64                                             `protobuf:"fixed64,5,opt,name=hasMoreData,proto3" json:"hasMoreData,omitempty"`
	SpellCheck       *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK       `protobuf:"bytes,6,opt,name=spellCheck,proto3" json:"spellCheck,omitempty"`
	AladinCard       *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD       `protobuf:"bytes,7,opt,name=aladinCard,proto3" json:"aladinCard,omitempty"`
	AdxParams        *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS        `protobuf:"bytes,8,opt,name=adxParams,proto3" json:"adxParams,omitempty"`
	NoResultLiuzi    *BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI    `protobuf:"bytes,9,opt,name=noResultLiuzi,proto3" json:"noResultLiuzi,omitempty"`
	NoResultReason   float64                                             `protobuf:"fixed64,10,opt,name=noResultReason,proto3" json:"noResultReason,omitempty"`
	LessResultReason float64                                             `protobuf:"fixed64,11,opt,name=lessResultReason,proto3" json:"lessResultReason,omitempty"`
	List             []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST           `protobuf:"bytes,12,rep,name=list,proto3" json:"list,omitempty"`
	Selected         *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED         `protobuf:"bytes,13,opt,name=selected,proto3" json:"selected,omitempty"`
	Keyword          string                                              `protobuf:"bytes,14,opt,name=keyword,proto3" json:"keyword,omitempty"`
	RecommendExtInfo *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO `protobuf:"bytes,15,opt,name=recommendExtInfo,proto3" json:"recommendExtInfo,omitempty"`
	NearWenan        string                                              `protobuf:"bytes,16,opt,name=nearWenan,proto3" json:"nearWenan,omitempty"`
	BsRecommendList  []string                                            `protobuf:"bytes,17,rep,name=bsRecommendList,proto3" json:"bsRecommendList,omitempty"` // TODO
	Tdk              *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK              `protobuf:"bytes,18,opt,name=tdk,proto3" json:"tdk,omitempty"`
	Breadcrumbs      []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS    `protobuf:"bytes,19,rep,name=breadcrumbs,proto3" json:"breadcrumbs,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetTotalCount() float64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetReturnCount() float64 {
	if x != nil {
		return x.ReturnCount
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetFbQueryId() string {
	if x != nil {
		return x.FbQueryId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetCurPage() float64 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetHasMoreData() float64 {
	if x != nil {
		return x.HasMoreData
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetSpellCheck() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK {
	if x != nil {
		return x.SpellCheck
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetAladinCard() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD {
	if x != nil {
		return x.AladinCard
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetAdxParams() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS {
	if x != nil {
		return x.AdxParams
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetNoResultLiuzi() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI {
	if x != nil {
		return x.NoResultLiuzi
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetNoResultReason() float64 {
	if x != nil {
		return x.NoResultReason
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetLessResultReason() float64 {
	if x != nil {
		return x.LessResultReason
	}
	return 0
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetList() []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetSelected() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetRecommendExtInfo() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO {
	if x != nil {
		return x.RecommendExtInfo
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetNearWenan() string {
	if x != nil {
		return x.NearWenan
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetBsRecommendList() []string {
	if x != nil {
		return x.BsRecommendList
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetTdk() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK {
	if x != nil {
		return x.Tdk
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST) GetBreadcrumbs() []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS {
	if x != nil {
		return x.Breadcrumbs
	}
	return nil
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 1}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 2}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 3}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardType        string                                                  `protobuf:"bytes,1,opt,name=cardType,proto3" json:"cardType,omitempty"`
	CityId          string                                                  `protobuf:"bytes,2,opt,name=cityId,proto3" json:"cityId,omitempty"`
	HouseCode       string                                                  `protobuf:"bytes,3,opt,name=houseCode,proto3" json:"houseCode,omitempty"`
	ResblockId      string                                                  `protobuf:"bytes,4,opt,name=resblockId,proto3" json:"resblockId,omitempty"`
	DelegateId      string                                                  `protobuf:"bytes,5,opt,name=delegateId,proto3" json:"delegateId,omitempty"`
	Title           string                                                  `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Desc            string                                                  `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	BangdanTitle    string                                                  `protobuf:"bytes,8,opt,name=bangdanTitle,proto3" json:"bangdanTitle,omitempty"`
	RecoDesc        string                                                  `protobuf:"bytes,9,opt,name=recoDesc,proto3" json:"recoDesc,omitempty"`
	TotalPrice      string                                                  `protobuf:"bytes,10,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	TotalPriceCount string                                                  `protobuf:"bytes,11,opt,name=totalPriceCount,proto3" json:"totalPriceCount,omitempty"`
	UnitPrice       string                                                  `protobuf:"bytes,12,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	JumpUrl         string                                                  `protobuf:"bytes,13,opt,name=jumpUrl,proto3" json:"jumpUrl,omitempty"`
	ListPictureUrl  *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL  `protobuf:"bytes,14,opt,name=listPictureUrl,proto3" json:"listPictureUrl,omitempty"`
	RecommendReason *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON `protobuf:"bytes,15,opt,name=recommendReason,proto3" json:"recommendReason,omitempty"`
	ColorTags       []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS     `protobuf:"bytes,16,rep,name=colorTags,proto3" json:"colorTags,omitempty"`
	HouseStatus     string                                                  `protobuf:"bytes,17,opt,name=houseStatus,proto3" json:"houseStatus,omitempty"`
	IsCtypeHouse    bool                                                    `protobuf:"varint,18,opt,name=isCtypeHouse,proto3" json:"isCtypeHouse,omitempty"`
	FbExpoId        string                                                  `protobuf:"bytes,19,opt,name=fbExpoId,proto3" json:"fbExpoId,omitempty"`
	StatusSwitch    *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH    `protobuf:"bytes,20,opt,name=statusSwitch,proto3" json:"statusSwitch,omitempty"`
	BrandTags       *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS       `protobuf:"bytes,21,opt,name=brandTags,proto3" json:"brandTags,omitempty"`
	RecomTag        []string                                                `protobuf:"bytes,22,rep,name=recomTag,proto3" json:"recomTag,omitempty"` // TODO
	HotTop          *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP          `protobuf:"bytes,23,opt,name=hotTop,proto3" json:"hotTop,omitempty"`
	FramePicture    []string                                                `protobuf:"bytes,24,rep,name=framePicture,proto3" json:"framePicture,omitempty"` // TODO
	HousePicture    []string                                                `protobuf:"bytes,25,rep,name=housePicture,proto3" json:"housePicture,omitempty"` // TODO
	MarketBooth     []string                                                `protobuf:"bytes,26,rep,name=marketBooth,proto3" json:"marketBooth,omitempty"`   // TODO
	PoiDistance     string                                                  `protobuf:"bytes,27,opt,name=poiDistance,proto3" json:"poiDistance,omitempty"`
	PoiIcon         string                                                  `protobuf:"bytes,28,opt,name=poiIcon,proto3" json:"poiIcon,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetHouseCode() string {
	if x != nil {
		return x.HouseCode
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetResblockId() string {
	if x != nil {
		return x.ResblockId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetDelegateId() string {
	if x != nil {
		return x.DelegateId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetBangdanTitle() string {
	if x != nil {
		return x.BangdanTitle
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetRecoDesc() string {
	if x != nil {
		return x.RecoDesc
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetTotalPriceCount() string {
	if x != nil {
		return x.TotalPriceCount
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetJumpUrl() string {
	if x != nil {
		return x.JumpUrl
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetListPictureUrl() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL {
	if x != nil {
		return x.ListPictureUrl
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetRecommendReason() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON {
	if x != nil {
		return x.RecommendReason
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetColorTags() []*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS {
	if x != nil {
		return x.ColorTags
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetHouseStatus() string {
	if x != nil {
		return x.HouseStatus
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetIsCtypeHouse() bool {
	if x != nil {
		return x.IsCtypeHouse
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetFbExpoId() string {
	if x != nil {
		return x.FbExpoId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetStatusSwitch() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH {
	if x != nil {
		return x.StatusSwitch
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetBrandTags() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS {
	if x != nil {
		return x.BrandTags
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetRecomTag() []string {
	if x != nil {
		return x.RecomTag
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetHotTop() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP {
	if x != nil {
		return x.HotTop
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetFramePicture() []string {
	if x != nil {
		return x.FramePicture
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetHousePicture() []string {
	if x != nil {
		return x.HousePicture
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetMarketBooth() []string {
	if x != nil {
		return x.MarketBooth
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetPoiDistance() string {
	if x != nil {
		return x.PoiDistance
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST) GetPoiIcon() string {
	if x != nil {
		return x.PoiIcon
	}
	return ""
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Price  *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE  `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Room   *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM   `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	More   *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE   `protobuf:"bytes,4,opt,name=more,proto3" json:"more,omitempty"`
	Order  *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER  `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) GetRegion() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) GetPrice() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) GetRoom() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) GetMore() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE {
	if x != nil {
		return x.More
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED) GetOrder() *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER {
	if x != nil {
		return x.Order
	}
	return nil
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizcircleId []string `protobuf:"bytes,1,rep,name=bizcircleId,proto3" json:"bizcircleId,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 6}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO) GetBizcircleId() []string {
	if x != nil {
		return x.BizcircleId
	}
	return nil
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Keywords    string `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 7}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 8}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 0}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 1}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Color     string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	TextColor string `protobuf:"bytes,4,opt,name=textColor,proto3" json:"textColor,omitempty"`
	BgColor   string `protobuf:"bytes,5,opt,name=bgColor,proto3" json:"bgColor,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 2}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsYeZhuTuijian bool `protobuf:"varint,1,opt,name=isYeZhuTuijian,proto3" json:"isYeZhuTuijian,omitempty"`
	IsHaofang      bool `protobuf:"varint,2,opt,name=isHaofang,proto3" json:"isHaofang,omitempty"`
	IsYezhuPay     bool `protobuf:"varint,3,opt,name=isYezhuPay,proto3" json:"isYezhuPay,omitempty"`
	IsVr           bool `protobuf:"varint,4,opt,name=isVr,proto3" json:"isVr,omitempty"`
	IsKey          bool `protobuf:"varint,5,opt,name=isKey,proto3" json:"isKey,omitempty"`
	IsNew          bool `protobuf:"varint,6,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 3}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsYeZhuTuijian() bool {
	if x != nil {
		return x.IsYeZhuTuijian
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsHaofang() bool {
	if x != nil {
		return x.IsHaofang
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsYezhuPay() bool {
	if x != nil {
		return x.IsYezhuPay
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsVr() bool {
	if x != nil {
		return x.IsVr
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsKey() bool {
	if x != nil {
		return x.IsKey
	}
	return false
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 4}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DspAgentUcId string  `protobuf:"bytes,1,opt,name=dspAgentUcId,proto3" json:"dspAgentUcId,omitempty"`
	HotTopDigV   string  `protobuf:"bytes,2,opt,name=hotTopDigV,proto3" json:"hotTopDigV,omitempty"`
	HotTop       float64 `protobuf:"fixed64,3,opt,name=hotTop,proto3" json:"hotTop,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 4, 5}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) GetDspAgentUcId() string {
	if x != nil {
		return x.DspAgentUcId
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) GetHotTopDigV() string {
	if x != nil {
		return x.HotTopDigV
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP) GetHotTop() float64 {
	if x != nil {
		return x.HotTop
	}
	return 0
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lev3 string   `protobuf:"bytes,3,opt,name=lev3,proto3" json:"lev3,omitempty"`
	Lev1 string   `protobuf:"bytes,4,opt,name=lev1,proto3" json:"lev1,omitempty"`
	Lev2 string   `protobuf:"bytes,5,opt,name=lev2,proto3" json:"lev2,omitempty"`
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5, 0}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) GetLev3() string {
	if x != nil {
		return x.Lev3
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) GetLev1() string {
	if x != nil {
		return x.Lev1
	}
	return ""
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION) GetLev2() string {
	if x != nil {
		return x.Lev2
	}
	return ""
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5, 1}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5, 2}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5, 3}
}

type BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER) Reset() {
	*x = BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beike_beike_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER) ProtoMessage() {}

func (x *BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER) ProtoReflect() protoreflect.Message {
	mi := &file_beike_beike_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER.ProtoReflect.Descriptor instead.
func (*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER) Descriptor() ([]byte, []int) {
	return file_beike_beike_proto_rawDescGZIP(), []int{0, 0, 0, 0, 5, 4}
}

var File_beike_beike_proto protoreflect.FileDescriptor

var file_beike_beike_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x65, 0x69, 0x6b, 0x65, 0x2f, 0x62, 0x65, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf9, 0x1e, 0x0a,
	0x05, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0xa0, 0x1e, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42,
	0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0xa7,
	0x1d, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x12, 0x58, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x45, 0x72,
	0x53, 0x68, 0x6f, 0x75, 0x46, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49,
	0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54,
	0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x52, 0x11,
	0x67, 0x65, 0x74, 0x45, 0x72, 0x53, 0x68, 0x6f, 0x75, 0x46, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0xc4, 0x1c, 0x0a, 0x11, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46,
	0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x62, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x62,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x63, 0x75, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x55, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54,
	0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c,
	0x49, 0x53, 0x54, 0x2e, 0x53, 0x50, 0x45, 0x4c, 0x4c, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x52, 0x0a,
	0x73, 0x70, 0x65, 0x6c, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x55, 0x0a, 0x0a, 0x61, 0x6c,
	0x61, 0x64, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44,
	0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48,
	0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x41, 0x4c, 0x41, 0x44, 0x49,
	0x4e, 0x43, 0x41, 0x52, 0x44, 0x52, 0x0a, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x52, 0x0a, 0x09, 0x61, 0x64, 0x78, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42,
	0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47,
	0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54,
	0x2e, 0x41, 0x44, 0x58, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x52, 0x09, 0x61, 0x64, 0x78, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x5e, 0x0a, 0x0d, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4c, 0x69, 0x75, 0x7a, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54,
	0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55,
	0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4e, 0x4f, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x4c, 0x49, 0x55, 0x5a, 0x49, 0x52, 0x0d, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4c, 0x69, 0x75, 0x7a, 0x69, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x6e,
	0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x2a, 0x0a,
	0x10, 0x6c, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x6c, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54,
	0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c,
	0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4f,
	0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52,
	0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x53, 0x45, 0x4c,
	0x45, 0x43, 0x54, 0x45, 0x44, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x67, 0x0a, 0x10, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45,
	0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45,
	0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e,
	0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x44, 0x45, 0x58, 0x54, 0x49, 0x4e, 0x46, 0x4f,
	0x52, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x61, 0x72, 0x57, 0x65, 0x6e, 0x61, 0x6e, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x61, 0x72, 0x57, 0x65, 0x6e, 0x61, 0x6e,
	0x12, 0x28, 0x0a, 0x0f, 0x62, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x73, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x03, 0x74, 0x64,
	0x6b, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54,
	0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c,
	0x49, 0x53, 0x54, 0x2e, 0x54, 0x44, 0x4b, 0x52, 0x03, 0x74, 0x64, 0x6b, 0x12, 0x58, 0x0a, 0x0b,
	0x62, 0x72, 0x65, 0x61, 0x64, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x73, 0x18, 0x13, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x36, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b,
	0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45,
	0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x42, 0x52,
	0x45, 0x41, 0x44, 0x43, 0x52, 0x55, 0x4d, 0x42, 0x53, 0x52, 0x0b, 0x62, 0x72, 0x65, 0x61, 0x64,
	0x63, 0x72, 0x75, 0x6d, 0x62, 0x73, 0x1a, 0x0c, 0x0a, 0x0a, 0x53, 0x50, 0x45, 0x4c, 0x4c, 0x43,
	0x48, 0x45, 0x43, 0x4b, 0x1a, 0x0c, 0x0a, 0x0a, 0x41, 0x4c, 0x41, 0x44, 0x49, 0x4e, 0x43, 0x41,
	0x52, 0x44, 0x1a, 0x0b, 0x0a, 0x09, 0x41, 0x44, 0x58, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x1a,
	0x0f, 0x0a, 0x0d, 0x4e, 0x4f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x4c, 0x49, 0x55, 0x5a, 0x49,
	0x1a, 0xb2, 0x0d, 0x0a, 0x04, 0x4c, 0x49, 0x53, 0x54, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x65, 0x73, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x6e, 0x67, 0x64, 0x61, 0x6e,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x6e,
	0x67, 0x64, 0x61, 0x6e, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x6f, 0x44, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x6f, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6a, 0x75, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6a, 0x75, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x66, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x3e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e,
	0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53,
	0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54,
	0x2e, 0x4c, 0x49, 0x53, 0x54, 0x50, 0x49, 0x43, 0x54, 0x55, 0x52, 0x45, 0x55, 0x52, 0x4c, 0x52,
	0x0e, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x69, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41,
	0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47,
	0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d,
	0x45, 0x4e, 0x44, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x09, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x54, 0x61, 0x67, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41,
	0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f,
	0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x43,
	0x4f, 0x4c, 0x4f, 0x52, 0x54, 0x41, 0x47, 0x53, 0x52, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x54,
	0x61, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x43, 0x74, 0x79, 0x70, 0x65,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43,
	0x74, 0x79, 0x70, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x62, 0x45,
	0x78, 0x70, 0x6f, 0x49, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x62, 0x45,
	0x78, 0x70, 0x6f, 0x49, 0x64, 0x12, 0x60, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41,
	0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46,
	0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x53, 0x57, 0x49, 0x54, 0x43, 0x48, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x57, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x54, 0x61, 0x67, 0x73, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e,
	0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41,
	0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x42, 0x52, 0x41, 0x4e,
	0x44, 0x54, 0x41, 0x47, 0x53, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x54, 0x61, 0x67, 0x18, 0x16, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x54, 0x61, 0x67, 0x12, 0x4e, 0x0a, 0x06,
	0x68, 0x6f, 0x74, 0x54, 0x6f, 0x70, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54,
	0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55,
	0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x48, 0x4f,
	0x54, 0x54, 0x4f, 0x50, 0x52, 0x06, 0x68, 0x6f, 0x74, 0x54, 0x6f, 0x70, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x18, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x19, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x74, 0x68, 0x18, 0x1a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x44, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x69,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x49,
	0x63, 0x6f, 0x6e, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x49, 0x63,
	0x6f, 0x6e, 0x1a, 0x10, 0x0a, 0x0e, 0x4c, 0x49, 0x53, 0x54, 0x50, 0x49, 0x43, 0x54, 0x55, 0x52,
	0x45, 0x55, 0x52, 0x4c, 0x1a, 0x11, 0x0a, 0x0f, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e,
	0x44, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x1a, 0x81, 0x01, 0x0a, 0x09, 0x43, 0x4f, 0x4c, 0x4f,
	0x52, 0x54, 0x41, 0x47, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0xb4, 0x01, 0x0a, 0x0c,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x53, 0x57, 0x49, 0x54, 0x43, 0x48, 0x12, 0x26, 0x0a, 0x0e,
	0x69, 0x73, 0x59, 0x65, 0x5a, 0x68, 0x75, 0x54, 0x75, 0x69, 0x6a, 0x69, 0x61, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x59, 0x65, 0x5a, 0x68, 0x75, 0x54, 0x75, 0x69,
	0x6a, 0x69, 0x61, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x48, 0x61, 0x6f, 0x66, 0x61, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x48, 0x61, 0x6f, 0x66, 0x61,
	0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x59, 0x65, 0x7a, 0x68, 0x75, 0x50, 0x61, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x59, 0x65, 0x7a, 0x68, 0x75, 0x50,
	0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x56, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x69, 0x73, 0x56, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4e,
	0x65, 0x77, 0x1a, 0x0b, 0x0a, 0x09, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x54, 0x41, 0x47, 0x53, 0x1a,
	0x64, 0x0a, 0x06, 0x48, 0x4f, 0x54, 0x54, 0x4f, 0x50, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x73, 0x70,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x73, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x63, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x68, 0x6f, 0x74, 0x54, 0x6f, 0x70, 0x44, 0x69, 0x67, 0x56, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x68, 0x6f, 0x74, 0x54, 0x6f, 0x70, 0x44, 0x69, 0x67, 0x56, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x6f, 0x74, 0x54, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68,
	0x6f, 0x74, 0x54, 0x6f, 0x70, 0x1a, 0xa8, 0x04, 0x0a, 0x08, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x12, 0x52, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49,
	0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54,
	0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x53,
	0x45, 0x4c, 0x45, 0x43, 0x54, 0x45, 0x44, 0x2e, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e,
	0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53,
	0x54, 0x2e, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x45, 0x44, 0x2e, 0x50, 0x52, 0x49, 0x43, 0x45,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x45, 0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e,
	0x47, 0x45, 0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53,
	0x54, 0x2e, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x45, 0x44, 0x2e, 0x52, 0x4f, 0x4f, 0x4d, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x4c, 0x0a, 0x04, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45,
	0x49, 0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45,
	0x54, 0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e,
	0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x45, 0x44, 0x2e, 0x4d, 0x4f, 0x52, 0x45, 0x52, 0x04, 0x6d,
	0x6f, 0x72, 0x65, 0x12, 0x4f, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x45, 0x49,
	0x4b, 0x45, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x44, 0x41, 0x54, 0x41, 0x2e, 0x47, 0x45, 0x54,
	0x45, 0x52, 0x53, 0x48, 0x4f, 0x55, 0x46, 0x41, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x54, 0x2e, 0x53,
	0x45, 0x4c, 0x45, 0x43, 0x54, 0x45, 0x44, 0x2e, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x1a, 0x68, 0x0a, 0x06, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x76, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x65, 0x76, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x76, 0x31, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x76, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65,
	0x76, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x76, 0x32, 0x1a, 0x07,
	0x0a, 0x05, 0x50, 0x52, 0x49, 0x43, 0x45, 0x1a, 0x06, 0x0a, 0x04, 0x52, 0x4f, 0x4f, 0x4d, 0x1a,
	0x06, 0x0a, 0x04, 0x4d, 0x4f, 0x52, 0x45, 0x1a, 0x07, 0x0a, 0x05, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x1a, 0x34, 0x0a, 0x10, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x44, 0x45, 0x58, 0x54,
	0x49, 0x4e, 0x46, 0x4f, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x69, 0x7a, 0x63, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x69, 0x7a, 0x63, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x59, 0x0a, 0x03, 0x54, 0x44, 0x4b, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x35, 0x0a, 0x0b, 0x42, 0x52, 0x45, 0x41, 0x44, 0x43, 0x52, 0x55, 0x4d, 0x42, 0x53,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x2e, 0x79,
	0x79, 0x75, 0x65, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62,
	0x65, 0x69, 0x6b, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beike_beike_proto_rawDescOnce sync.Once
	file_beike_beike_proto_rawDescData = file_beike_beike_proto_rawDesc
)

func file_beike_beike_proto_rawDescGZIP() []byte {
	file_beike_beike_proto_rawDescOnce.Do(func() {
		file_beike_beike_proto_rawDescData = protoimpl.X.CompressGZIP(file_beike_beike_proto_rawDescData)
	})
	return file_beike_beike_proto_rawDescData
}

var file_beike_beike_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_beike_beike_proto_goTypes = []interface{}{
	(*BEIKE)(nil),                                                  // 0: message.BEIKE
	(*BEIKE_DATA)(nil),                                             // 1: message.BEIKE.DATA
	(*BEIKE_DATA_DATA)(nil),                                        // 2: message.BEIKE.DATA.DATA
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST)(nil),                      // 3: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK)(nil),           // 4: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SPELLCHECK
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD)(nil),           // 5: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.ALADINCARD
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS)(nil),            // 6: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.ADXPARAMS
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI)(nil),        // 7: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.NORESULTLIUZI
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST)(nil),                 // 8: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED)(nil),             // 9: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO)(nil),     // 10: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.RECOMMENDEXTINFO
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK)(nil),                  // 11: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.TDK
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS)(nil),          // 12: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.BREADCRUMBS
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL)(nil),  // 13: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.LISTPICTUREURL
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON)(nil), // 14: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.RECOMMENDREASON
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS)(nil),       // 15: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.COLORTAGS
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH)(nil),    // 16: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.STATUSSWITCH
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS)(nil),       // 17: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.BRANDTAGS
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP)(nil),          // 18: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.HOTTOP
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION)(nil),      // 19: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.REGION
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE)(nil),       // 20: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.PRICE
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM)(nil),        // 21: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.ROOM
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE)(nil),        // 22: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.MORE
	(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER)(nil),       // 23: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.ORDER
}
var file_beike_beike_proto_depIdxs = []int32{
	1,  // 0: message.BEIKE.data:type_name -> message.BEIKE.DATA
	2,  // 1: message.BEIKE.DATA.data:type_name -> message.BEIKE.DATA.DATA
	3,  // 2: message.BEIKE.DATA.DATA.getErShouFangList:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST
	4,  // 3: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.spellCheck:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SPELLCHECK
	5,  // 4: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.aladinCard:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.ALADINCARD
	6,  // 5: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.adxParams:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.ADXPARAMS
	7,  // 6: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.noResultLiuzi:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.NORESULTLIUZI
	8,  // 7: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.list:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST
	9,  // 8: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.selected:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED
	10, // 9: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.recommendExtInfo:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.RECOMMENDEXTINFO
	11, // 10: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.tdk:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.TDK
	12, // 11: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.breadcrumbs:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.BREADCRUMBS
	13, // 12: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.listPictureUrl:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.LISTPICTUREURL
	14, // 13: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.recommendReason:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.RECOMMENDREASON
	15, // 14: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.colorTags:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.COLORTAGS
	16, // 15: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.statusSwitch:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.STATUSSWITCH
	17, // 16: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.brandTags:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.BRANDTAGS
	18, // 17: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.hotTop:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.LIST.HOTTOP
	19, // 18: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.region:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.REGION
	20, // 19: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.price:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.PRICE
	21, // 20: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.room:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.ROOM
	22, // 21: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.more:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.MORE
	23, // 22: message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.order:type_name -> message.BEIKE.DATA.DATA.GETERSHOUFANGLIST.SELECTED.ORDER
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_beike_beike_proto_init() }
func file_beike_beike_proto_init() {
	if File_beike_beike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beike_beike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SPELLCHECK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ALADINCARD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_ADXPARAMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_NORESULTLIUZI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_RECOMMENDEXTINFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_TDK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_BREADCRUMBS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_LISTPICTUREURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_RECOMMENDREASON); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_COLORTAGS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_STATUSSWITCH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_BRANDTAGS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_LIST_HOTTOP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_REGION); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_PRICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_MORE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beike_beike_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEIKE_DATA_DATA_GETERSHOUFANGLIST_SELECTED_ORDER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beike_beike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beike_beike_proto_goTypes,
		DependencyIndexes: file_beike_beike_proto_depIdxs,
		MessageInfos:      file_beike_beike_proto_msgTypes,
	}.Build()
	File_beike_beike_proto = out.File
	file_beike_beike_proto_rawDesc = nil
	file_beike_beike_proto_goTypes = nil
	file_beike_beike_proto_depIdxs = nil
}
