CREATE TABLE IF NOT EXISTS "beike" (
    "house_code" INT,
    "card_type" TEXT,
    "city_id" INT,
    "resblock_id" INT,
    "delegate_id" INT,
    "title" TEXT,
    "desc" TEXT,
    "bangdan_title" TEXT,
    "reco_desc" TEXT,
    "total_price" TEXT,
    "total_price_count" INT,
    "unit_price" TEXT,
    "jump_url" TEXT,
    "list_picture_url" TEXT,
    "recommend_reason" INT,
    "color_tags" JSON,
    -- "colorTags_title" TEXT,
    -- "colorTags_color" TEXT,
    -- "colorTags_textColor" TEXT,
    -- "colorTags_bgColor" TEXT,
    "house_status" INT,
    "is_ctype_house" TEXT,
    "fb_expo_id" INT,
    "status_switch" JSON,
    -- "statusSwitch_isYeZhuTuijian" TEXT,
    -- "statusSwitch_isHaofang" TEXT,
    -- "statusSwitch_isYezhuPay" TEXT,
    -- "statusSwitch_isVr" TEXT,
    -- "statusSwitch_isKey" TEXT,
    -- "statusSwitch_isNew" TEXT,
    -- "brand_tags" JSON,
    "hot_top" JSON,
    -- "hotTop_dspAgentUcId" INT,
    -- "hotTop_hotTopDigV" INT,
    -- "hotTop_hotTop" INT,
    "poi_distance" INT,
    "poi_icon" INT,
    "frame_picture" JSON,
    -- "framePicture_url" TEXT,
    -- "framePicture_type" TEXT,
    "house_picture" JSON,
    -- "housePicture_url" TEXT,
    -- "housePicture_type" TEXT,
    "market_booth" JSON,
    -- "marketBooth_type" TEXT,
    -- "marketBooth_title" TEXT,
    -- "marketBooth_iconUrl" TEXT,
    -- "marketBooth_textColor" TEXT,
    -- "marketBooth_bgColor" TEXT,
    "brand_tags" JSON,
    -- "brandTags_title" TEXT,
    -- "brandTags_picUrl" TEXT
    PRIMARY KEY ("house_code")
);