// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Success Status = 0
	Status_Info    Status = 1
	Status_Warning Status = 2
	Status_Error   Status = 3
)

var Status_name = map[int32]string{
	0: "Success",
	1: "Info",
	2: "Warning",
	3: "Error",
}

var Status_value = map[string]int32{
	"Success": 0,
	"Info":    1,
	"Warning": 2,
	"Error":   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{0}
}

type Message struct {
	State                Status   `protobuf:"varint,1,opt,name=state,proto3,enum=message.Status" json:"state,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetState() Status {
	if m != nil {
		return m.State
	}
	return Status_Success
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.Status", Status_name, Status_value)
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("common/message.proto", fileDescriptor_8de410db4f60bbbc) }

var fileDescriptor_8de410db4f60bbbc = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x72, 0x95, 0xbc, 0xb8, 0xd8, 0x7d, 0x21, 0x4c, 0x21, 0x55, 0x2e, 0xd6, 0xe2,
	0x92, 0xc4, 0x92, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x7e, 0x3d, 0x98, 0x96, 0xe0,
	0x92, 0xc4, 0x92, 0xd2, 0xe2, 0x20, 0x88, 0xac, 0x90, 0x04, 0x17, 0x4c, 0xb3, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x65, 0xce, 0xc5, 0x06, 0x51, 0x2a, 0xc4, 0xcd, 0xc5, 0x1e,
	0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x2c, 0xc0, 0x20, 0xc4, 0xc1, 0xc5, 0xe2, 0x99, 0x97, 0x96,
	0x2f, 0xc0, 0x08, 0x12, 0x0e, 0x4f, 0x2c, 0xca, 0xcb, 0xcc, 0x4b, 0x17, 0x60, 0x12, 0xe2, 0xe4,
	0x62, 0x75, 0x2d, 0x2a, 0xca, 0x2f, 0x12, 0x60, 0x76, 0x92, 0x89, 0x92, 0x4a, 0xcf, 0xd7, 0xab,
	0xac, 0x2c, 0x4d, 0xd5, 0x4b, 0x49, 0x2d, 0xd3, 0x47, 0x75, 0x71, 0x12, 0x1b, 0xd8, 0xc9, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x14, 0xb0, 0x65, 0xca, 0x00, 0x00, 0x00,
}
